--DB: NERDBOOK, user: adminUser, pass: admin ;
CREATE TABLE posttype (
    posttype_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    posttype_nome VARCHAR(32)
);

CREATE TABLE utenti (
    utente_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(256),
    cognome VARCHAR(256),
    username VARCHAR(128) UNIQUE,
    password VARCHAR(256) NOT NULL,
    urlFotoProfilo VARCHAR(256)
);

CREATE TABLE posts (
    post_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contenuto VARCHAR(1024),
    type INTEGER,FOREIGN KEY (type) REFERENCES posttype(posttype_id),
    author INTEGER,FOREIGN KEY (author) REFERENCES utenti(utente_id)
);

CREATE TABLE gruppi (
	gruppo_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nome VARCHAR(256),
	urlFotoProfilo VARCHAR(256)
);

CREATE TABLE membri (
	id_utente INTEGER, FOREIGN KEY (id_utente) REFERENCES utenti(utente_id),
	id_gruppo INTEGER, FOREIGN KEY (id_gruppo) REFERENCES gruppi(gruppo_id)
);

--popolamento

INSERT INTO utenti(utente_id,nome,cognome,username,password,urlFotoProfilo)
VALUES(default,'Cappellaio','Matto','cappellaio','123','img/cappellaio.jpg');

INSERT INTO utenti(utente_id,nome,cognome,username,password,urlFotoProfilo)
VALUES(default,'Stregatto','Gatto','stregatto','123','img/stregatto.jpg');

INSERT INTO utenti(utente_id,nome,cognome,username,password,urlFotoProfilo)
VALUES(default,'Pinco','Panco','pincopanco','123','img/pincopanco.jpg');

INSERT INTO posttype (post_id, name)
VALUES (default, 'TEXT');

INSERT INTO posttype (post_id, name)
VALUES (default, 'IMAGE');

INSERT INTO posts (post_id, contenuto, type, author)
VALUES (default,'bla bla bla',1,0);

INSERT INTO posts (post_id, contenuto, type, author)
VALUES (default,'img/cibo.jpg',2,1);

INSERT INTO posts (post_id, contenuto, type, author)
VALUES (default,'http://it.wikihow.com/Creare-un-Cappello',1,2);

INSERT INTO gruppi (gruppo_id,nome,urlFotoProfilo)
VALUES (default,"ritardatari","");

INSERT INTO gruppi (gruppo_id,nome,urlFotoProfilo)
VALUES (default,"mongolfieristi","");

INSERT INTO membri (gruppo_id,utente_id)
VALUES (0,1);

INSERT INTO membri (gruppo_id,utente_id)
VALUES (0,2);

INSERT INTO membri (gruppo_id,utente_id)
VALUES (1,0);

INSERT INTO membri (gruppo_id,utente_id)
VALUES (1,2);


